version: 0.2

env:
    variables:

APP_NAME: "Imagefootagenew"
BUILD_ENV : "prod"

phases:
  build:
        commands:
        # Builds Angular application. You can also build using custom environment here like mock or staging
        - echo Build started on `date`
        - ng build --${BUILD_ENV}
artifacts:
    files:
        - '/'
    discard-paths: yes
    base-directory: 'dist*'
